### ISSUE TITLE
Running the command

### ISSUE THREAD

**Issue by emptyr1** [aaronmboyd/docker-xmrMiner#4]
hey great work here. I was having issues running the docker command.
```
$~  sudo nvidia-docker run aaronmboyd/xmrminer --url=stratum+tcp://mine.xmrpool.net:5555 --launch=10x24 --bfactor=4 --bsleep=100 --user=mudit.bodom@gmail.com -p docker_worker_1 --donate=3

 psychocrypt's XMR donation address:
   43NoJVEXo21hGZ6tDG6Z3g4qimiGdJPE6GRxAmiWwm26gwr62Lqo7zRiCJFSBmbkwTGNuuES9ES5TgaVHceuYc4Y75txCTU
 for more donation addresses please read the README.md
-----------------------------------------------------------------
[2017-08-26 23:37:49] Using JSON-RPC 2.0
[2017-08-26 23:37:49] Starting Stratum on stratum+tcp://mine.xmrpool.net:5555
[2017-08-26 23:37:49] Stratum authentication failed
[2017-08-26 23:37:49] ...retry after 30 seconds
[2017-08-26 23:37:51] 1 miner threads started, using 'cryptonight' algorithm.
[2017-08-26 23:37:51] GPU #0: Tesla M60 (16 SMX), using 24 blocks of 10 threads
[2017-08-26 23:37:51] GPU #0: Warning: block count 24 is not a multiple of SMX count 16.
[2017-08-26 23:37:54] GPU #0: Tesla M60, 260.63 H/s
/[2017-08-26 23:38:19] Stratum authentication failed
[2017-08-26 23:38:19] ...retry after 30 seconds
```
I believe this is the launch parameters issue? How can I solve this? I'm using the [g3.4xlarge](https://aws.amazon.com/ec2/pricing/on-demand/) instance on AWS which has 16 vCPU, 47 ECU and 122 GB memory

**Comment by aaronmboyd** [comment]
@modqhx ,

This Docker image is specifically for running [xmrMiner](https://github.com/xmrMiner/xmrMiner) which is a Monero miner for NVIDIA CUDA-enabled graphics cards.

Are you CPU mining or GPU mining on your cloud instance? Edit: Aaah, I see that is a GPU instance, nice.

Regardless, looks like you've used the wrong parameters here. The ``--user=`` launch parameter is for your Monero address to pay the mining output to. The ``-p`` tag is normally for your email or some identifier for your miner.

Check the [xmrMiner](https://github.com/xmrMiner/xmrMiner) page for details on the launch parameters. Or edit one of the example run commands I posted in the ReadMe for this project.

**Comment by aaronmboyd** [comment]
Also, you should check the CUDA capacity of the card so you can set the ``--launch`` parameters to fully utilise the instance's graphics card (looks to be Tesla M60).

**Comment by emptyr1** [comment]
@aaronmboyd Thanks. Yes, I'm running it on a NVIDIA(+cuda) GPU. OkI got a separate monero address from MyMonero. Can you tell how to get this cuda capacity of the card, that  you mention? For setting the `launch` parameter.. I've cuda and other stuff installed.

**Comment by aaronmboyd** [comment]
Take a look at the "Performance" section of the [xmrMiner project](https://github.com/xmrMiner/xmrMiner) readme for information on how to set your ``--launch`` parameters.

I can see from the output you posted here this card has 16 multiprocessors so you need to set the ``b`` part of the ``t x b`` equation to be a multiple of 16. I'm not sure how many threads you should use, but a good start would be to [check the specifications for the card](https://images.nvidia.com/content/tesla/pdf/188417-Tesla-M60-DS-A4-fnl-Web.pdf) and then go from there. Try a few different values and see which gives the best performance. 

I can also [see that this card has a compute capacity of 5.2](https://developer.nvidia.com/cuda-gpus) so you might be subject to the RAM restrictions as noted in the xmrMiner project page.

If you're having troubles, please raise a query on that project - I'm not the author of xmrMiner, I just packaged it up into a Docker image for ease of use.

**Comment by emptyr1** [comment]
Great thanks @aaronmboyd ! One last question I had is, if I am getting a hash rate of 13000 H/s. Would you recommend mining solo or pool? If solo, is there an option with mine solo with this repo?

**Comment by aaronmboyd** [comment]
You can solo mine with some pools. For example xmrpool has a solo mining port. You would just need to change the stratum url when launching. Check out a few pools to see if they have a solo mining option.

**Comment by emptyr1** [comment]
@aaronmboyd Thanks! I'll look into xmr pool. I was infact looking for recommendation, at a 13 KH/s if you recommend solo or pool. :) Also another thing I meant to ask is: let's say I'm able to run this docker image ONLY on the weekends. Hence I stop the image and run it again. Is there any concept of _"lost work"_ (or even duplicate work) when I'm stopping and re-launching the container? Does it periodically save any _**work**_ on disk? I see it finds a block every few seconds, I'm using XMR address from mymonero.com(which doesn't show "fraction of XMR" balance but only whole numbers) .. Sorry about the NOOBS questions. Cheers

**Comment by aaronmboyd** [comment]
Hi @modqhx ,

Well, in _theory_, in the long run (as time approaches infinity) it shouldn't matter if you pool or solo mine. If you pool mine you'll get lots of little payments over time and statistical variance (luck) of the pool is ironed out a bit for you. 

If you solo mine you'll get infrequent large payments (an entire block reward!) only when you solve a block, but lots of variance. You might have many weeks before solving a block and a string of bad luck can make earning consistently difficult.

I only mine around 1KH/s so for me pool mining makes the most sense as I can see a small trickle of consistent earnings. Maybe have a chat with some others online to see what would be best for you situation.

As for "lost work" - that's not really how Docker containers work (mostly, it _is_ possible to save the changed state of the container but it's not required here). Think of it more as an immutable operating environment for xmrMiner, that's all. There is nothing to save to disk here because you are connecting to a remote pool and receiving and posting your hashes to that address. You are not syncing the blockchain or "storing" anything here. Have a read through some Docker tutorials to find out more.

**Comment by emptyr1** [comment]
@aaronmboyd Great thanks for sharing! I do know about docker containers, but not about specifics of mining xmr. Okay, so what I'm understanding from you. It doesn't matter how many times I stop or start the this mining service(aka docker container). Was asking since I only have access to machines only on weekend. thanks again :)
