### ISSUE TITLE
wallet address

### ISSUE THREAD

**Issue by renderit** [aaronmboyd/docker-xmrMiner#5]
Hi, trying to run the nvidia docker image. Runs fine! :) I wanted to ask about getting a wallet address. I tried searching online, but not much luck. I got a wallet address from `mymonero.com` however I'm reading that the exchange also needs to support mining, which I believe it doesn't. How and where should I get a monero address specifically for running this image for mining? Thanks!

**Comment by aaronmboyd** [comment]
I haven't used mymonero.com but generally I would recommend running your own Monero daemon and creating a wallet that way. I don't know what "the exchange also needs to support mining" means - it doesn't make sense to me. A wallet is simply a cryptographic keyring that provides access to tokens on the blockchain - it doesn't "know" or care what the source is. You are mining on your computer, not on the exchange, so they don't need to know anything about it. I've never heard of any restrictions like this so it might be a misunderstanding or misreading of something else. 

Check out the downloads page on the official Monero website: https://getmonero.org/downloads/ to get and run the Monero daemon. There's even a beta GUI which works quite well also.

The caveat with this approach is that you are running a full node and will have to wait for the blockchain to sync - which can take some time and use up hard drive space, but it does give you the most control.
